"""initial schema

Revision ID: 228c03f0c7d9
Revises: 
Create Date: 2026-07-14 15:53:35.339264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '228c03f0c7d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('careers_url', sa.Text(), nullable=True),
    sa.Column('careers_url_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('preferred_strategy', sa.String(length=32), nullable=True),
    sa.Column('last_crawl_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("health IN ('unknown','healthy','degraded','failing')", name='ck_company_health'),
    sa.CheckConstraint("status IN ('active','paused','deleted')", name='ck_company_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discovery_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('include','requirement','exclude')", name='ck_keyword_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term', 'kind', name='uq_keyword_term_kind')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('companies_total', sa.Integer(), nullable=False),
    sa.Column('companies_ok', sa.Integer(), nullable=False),
    sa.Column('companies_failed', sa.Integer(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_matched', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hour', sa.SmallInteger(), nullable=False),
    sa.Column('minute', sa.SmallInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('hour >= 0 AND hour <= 23', name='ck_schedule_hour'),
    sa.CheckConstraint('minute >= 0 AND minute <= 59', name='ck_schedule_minute'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hour', 'minute', name='uq_schedule_time')
    )
    op.create_table('settings',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('notification_email', sa.Text(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('match_threshold', sa.Float(), nullable=False),
    sa.Column('requirement_boost', sa.Float(), nullable=False),
    sa.Column('scan_concurrency', sa.SmallInteger(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=16), nullable=False),
    sa.Column('discovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_settings_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('strategies_attempted', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_matched', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_results_company_id'), 'crawl_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_crawl_results_scan_run_id'), 'crawl_results', ['scan_run_id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scan_run_id', sa.String(length=36), nullable=True),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=False),
    sa.Column('description_snippet', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_state', sa.String(length=16), nullable=False),
    sa.Column('user_state_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_strategy', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('discovery_query_id', sa.String(length=36), nullable=True),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('new','matched','excluded','unmatched')", name='ck_job_status'),
    sa.CheckConstraint("user_state IN ('none','bookmarked','applied')", name='ck_job_user_state'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['discovery_query_id'], ['discovery_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('email_log_jobs',
    sa.Column('email_log_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['email_log_id'], ['email_logs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('email_log_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_log_jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_crawl_results_scan_run_id'), table_name='crawl_results')
    op.drop_index(op.f('ix_crawl_results_company_id'), table_name='crawl_results')
    op.drop_table('crawl_results')
    op.drop_table('settings')
    op.drop_table('schedules')
    op.drop_table('scan_runs')
    op.drop_table('keywords')
    op.drop_table('discovery_queries')
    op.drop_table('companies')
    # ### end Alembic commands ###
